name: yatrigan
description: Yatrigan

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.5.0
  provider: ^6.0.3
  sqflite: ^2.2.8+2
  http_parser: ^4.0.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.2.1
  connectivity_plus: ^7.0.0
  flutter_carousel_widget: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - images/main/
    - images/main/ir/
    - images/main/prod/
