name: yatrigan
description: Yatrigan

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.3
  http_parser: ^4.0.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.2.1
  connectivity_plus: ^3.0.2
  flutter_carousel_widget: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/main/home/
    - images/main/indianrailways/